### ISSUE TITLE
Terraform поменял лицензию

### ISSUE THREAD

**Issue by nikolaymatrosov** [yandex-cloud-examples/yc-vm-group-with-autoscale#1]
> Terraform и его провайдеры распространяются под лицензией Mozilla Public License.

Это утверждение из README.md более не верно.

**Comment by ka1bi4** [comment]
@nikolaymatrosov 
Спасибо, поправим в https://github.com/yandex-cloud-examples/yc-vm-group-with-autoscale/pull/2

**Comment by vnkiryushkin** [comment]
Убрал информацию о лицензиях TF и его провайдеров. В этом репозитории мы их не выкладываем. Ишью закрываю, спасибо.
